// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjyihxmftenxmcmgwedh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqeWloeG1mdGVueG1jbWd3ZWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzM3MTcsImV4cCI6MjA1OTYwOTcxN30.0bBcE15I4c-L8V_TG7sOuJPPZLRp9xuvhxaX_ieYK-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);